# Generated by Django 5.0.6 on 2026-09-20 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada — llegó mercancía'), ('venta', 'Venta — salió por un pedido'), ('salida', 'Salida — se usó o se dañó'), ('devolucion', 'Devolución — volvió al inventario'), ('ajuste', 'Ajuste — corrección por conteo físico')], max_length=12)),
                ('cantidad', models.PositiveIntegerField(help_text='Siempre en positivo. El signo lo da el tipo de movimiento.')),
                ('stock_antes', models.PositiveIntegerField(editable=False)),
                ('stock_despues', models.PositiveIntegerField(editable=False)),
                ('motivo', models.CharField(blank=True, help_text='Opcional, pero muy útil dentro de seis meses. Ej: conteo del 30/09, llegó pedido a proveedor, se dañó al instalar.', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.variante')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-creado', '-id'],
                'indexes': [models.Index(fields=['variante', '-creado'], name='inventario__variant_64d1ac_idx')],
            },
        ),
    ]
