# Generated by Django 5.0.6 on 2026-09-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Se arma solo con el nombre. Es la dirección web: cambiarlo rompe los enlaces que ya estén circulando.', max_length=90, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Un par de frases. Sale arriba del listado y en el buscador de Google.')),
                ('imagen', models.ImageField(blank=True, help_text='Opcional. Se ve en la portada del catálogo.', upload_to='dacars/catalogo/categorias')),
                ('servicio', models.CharField(blank=True, choices=[('ppf-villavicencio', 'PPF'), ('polarizados-villavicencio', 'Polarizados'), ('detailing-villavicencio', 'Detailing'), ('accesorios-4x4-villavicencio', 'Accesorios 4x4'), ('lujos-y-accesorios-villavicencio', 'Lujos y accesorios'), ('iluminacion-para-carros-villavicencio', 'Iluminación'), ('sonido-para-carros-villavicencio', 'Sonido'), ('llantas-villavicencio', 'Llantas'), ('pdr-desabolladura-sin-pintura-villavicencio', 'PDR')], help_text='Enlaza la categoría con su página de servicio.', max_length=60, verbose_name='servicio relacionado')),
                ('orden', models.PositiveSmallIntegerField(default=100, help_text='Menor número, más arriba.')),
                ('activa', models.BooleanField(default=True, help_text='Desmarcá para esconderla del sitio sin borrarla.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='dacars/catalogo/marcas')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, help_text='Se arma solo con el nombre.', max_length=160, unique=True)),
                ('resumen', models.CharField(blank=True, help_text='Una línea. Es lo que se lee en la tarjeta del listado.', max_length=180)),
                ('descripcion', models.TextField(blank=True, help_text='El texto largo de la ficha. Un párrafo por línea en blanco.')),
                ('caracteristicas', models.TextField(blank=True, help_text='Una por línea. Se muestran como lista con viñetas.', verbose_name='características')),
                ('compatibilidad', models.CharField(blank=True, help_text='Con qué vehículos sirve. Ej: Hilux, Ranger, Amarok, D-Max.', max_length=240)),
                ('instalacion', models.BooleanField(default=True, help_text='Si está marcado, la ficha avisa que la instalación va incluida o se cotiza aparte.', verbose_name='se instala en el taller')),
                ('destacado', models.BooleanField(default=False, help_text='Aparece primero en el catálogo y en la portada.')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcá para sacarlo del sitio sin borrarlo.')),
                ('orden', models.PositiveSmallIntegerField(default=100)),
                ('seo_titulo', models.CharField(blank=True, help_text='Máximo 70 caracteres. Vacío = se usa el nombre del producto.', max_length=70, verbose_name='título para Google')),
                ('seo_descripcion', models.CharField(blank=True, help_text='Máximo 160 caracteres. Vacío = se usa el resumen.', max_length=160, verbose_name='descripción para Google')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.marca')),
            ],
            options={
                'ordering': ['-destacado', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='dacars/catalogo/productos')),
                ('alt', models.CharField(blank=True, help_text='Qué se ve en la foto. Lo lee Google y los lectores de pantalla. Vacío = se arma con el nombre del producto.', max_length=160, verbose_name='texto alternativo')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='La de menor número es la principal.')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Ej: 265/65R17, 35%, Talla M. Dejalo vacío si el producto no tiene variantes.', max_length=120, verbose_name='medida o presentación')),
                ('sku', models.CharField(blank=True, help_text='Código interno. Si lo dejás vacío se genera solo.', max_length=40, unique=True, verbose_name='SKU')),
                ('precio', models.DecimalField(decimal_places=0, help_text='En pesos, sin puntos ni centavos. Ej: 450000', max_digits=12)),
                ('precio_antes', models.DecimalField(blank=True, decimal_places=0, help_text='Opcional. Si lo llenás, se muestra tachado al lado del precio.', max_digits=12, null=True, verbose_name='precio anterior')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Unidades físicas en el local.', verbose_name='existencias')),
                ('reservado', models.PositiveIntegerField(default=0, editable=False, help_text='Unidades comprometidas por pedidos sin confirmar. Lo maneja el sistema.')),
                ('stock_minimo', models.PositiveIntegerField(default=2, help_text='Cuando queden estas unidades o menos, salta la alerta en el tablero.', verbose_name='mínimo')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes y existencias',
                'ordering': ['producto', 'orden', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'categoria'], name='catalogo_pr_activo_01843d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='catalogo_pr_slug_17e2cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='variante_unica_por_producto'),
        ),
    ]
