# Generated by Django 6.0.4 on 2026-09-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='servicio',
            field=models.CharField(blank=True, choices=[('ppf-villavicencio', 'PPF'), ('polarizados-villavicencio', 'Polarizados'), ('detailing-villavicencio', 'Detailing'), ('accesorios-4x4-villavicencio', 'Accesorios 4x4'), ('lujos-y-accesorios-villavicencio', 'Lujos y accesorios'), ('iluminacion-para-carros-villavicencio', 'Iluminación'), ('sonido-para-carros-villavicencio', 'Sonido'), ('llantas-villavicencio', 'Llantas'), ('pdr-desabolladura-sin-pintura-villavicencio', 'PDR'), ('pintura-automotriz-villavicencio', 'Pintura')], help_text='Enlaza la categoría con su página de servicio.', max_length=60, verbose_name='servicio relacionado'),
        ),
    ]
