# Generated by Django 6.0.4 on 2026-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_categoria_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='referencia',
            field=models.BooleanField(default=False, help_text='Marcala si no es una foto real de este producto (generada con IA o sacada del fabricante). La ficha le pone la etiqueta «Imagen de referencia», para no prometer algo que no es exactamente así.', verbose_name='imagen de referencia'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'El producto'), ('instalado', 'Instalado en un carro')], default='producto', help_text='«Instalado» es la que muestra la tarjeta al pasar el mouse.', max_length=12),
        ),
    ]
