# Generated by Django 5.0.6 on 2026-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_foto_tipo_y_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Lo que te costó a vos. No sale nunca en la web: sirve para saber cuánto estás ganando.', max_digits=12, null=True, verbose_name='costo de compra'),
        ),
    ]
