# Generated by Django 5.0.6 on 2026-09-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo — sin responder'), ('confirmado', 'Confirmado — se descontó del inventario'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='nuevo', max_length=12)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del cliente')),
                ('telefono', models.CharField(max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('ciudad', models.CharField(default='Villavicencio', max_length=80)),
                ('direccion', models.CharField(blank=True, help_text='Solo si lo quieren enviado. Vacío = pasa a recogerlo.', max_length=200, verbose_name='dirección')),
                ('vehiculo', models.CharField(blank=True, help_text='Ej: Toyota Hilux 2022. Sirve para confirmar que el repuesto le sirve.', max_length=120, verbose_name='vehículo')),
                ('notas', models.TextField(blank=True, verbose_name='notas del cliente')),
                ('notas_internas', models.TextField(blank=True, help_text='No lo ve el cliente. Para el equipo.')),
                ('total', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12)),
                ('stock_descontado', models.BooleanField(default=False, editable=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('confirmado_en', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado', '-creado'], name='pedidos_ped_estado_94c3d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=220, verbose_name='descripción')),
                ('sku', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='catalogo.variante')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'producto del pedido',
                'verbose_name_plural': 'productos del pedido',
            },
        ),
    ]
