# Generated by Django 5.0.6 on 2026-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Lo que costaba la variante cuando se vendió. Vacío si no estaba cargado.', max_digits=12, null=True),
        ),
    ]
